server:
  port: 9190

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: james
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
      expiration: 60000 # test 1 minute.
      refresh-token:
        expiration: 604800000 # 7 days
